### ISSUE TITLE
Can not install ndb with yarn

### ISSUE THREAD

**Issue by RushPu** [GoogleChromeLabs/ndb#163]
### Steps to reproduce
➜  yarn global add ndb
yarn global v1.7.0
[1/4] 🔍  Resolving packages...
⠁ (node:29302) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] 🚚  Fetching packages...
error http://47.97.71.190:4873/capture-stack-trace/-/capture-stack-trace-1.0.1.tgz: Fetch succeeded for "capture-stack-trace". However, extracting "http://47.97.71.190:4873/capture-stack-trace/-/capture-stack-trace-1.0.1.tgz" resulted in hash "a6c0bbe1f38f3aa0b92238ecb6ff42c344d4135d", which did not match the requested hash "ed0a1edb87c05d4db1037c5f8f483d8a3b5f0825".
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

**Tell us about your environment:**

* ndb version:
* Platform / OS version: macos high sierra
* Node.js version: v10.7.0
* yarn version: 1.7.0

**Comment by ak239** [comment]
Unfortunately I can not reproduce this issue locally. We do not have yarn.lock file in ndb repository so I believe that this issue is unrelated to ndb but something related to yarn and capture stack traces package.
We updated most packages in latest release so I hope that this issue is fixed.
Feel free to comment if you can reproduce this one with latest ndb.
