### ISSUE TITLE
Error messages aren't visible.

### ISSUE THREAD

**Issue by NicholasJohn16** [GoogleChromeLabs/ndb#251]
For some reason, I can't view some error messages in the console. Instead, all I see is a red line. This seems to happen whenever there's a bug in my code earlier on and just when ndb is just starting up.

![errors](https://user-images.githubusercontent.com/1107114/56939123-81837d80-6ad4-11e9-93ba-6b6b47bc3911.png)

### Steps to reproduce
* ndb version: 1.0.44
* Platform / OS version: Windows 10
* Node.js version: 8.11.4

**What steps will reproduce the problem?**
On one occasion, I had accidentally called a function using like `object::function` instead of `object.function`. Though, it's been caused by other errors, as well.

**Comment by ak239** [comment]
Could you check latest ndb version: `1.0.47`? This issue should be fixed there.

**Comment by ak239** [comment]
I checked `1.0.49` and can not reproduce this issue with repro case that works with `1.0.44` so I assume this one was fixed by rolling DevTools frontend and by implementing from scratch detecting and attaching to node process. Feel free to left a comment here or file another issue if you still can reproduce this bug.
