### ISSUE TITLE
Chrome icon color

### ISSUE THREAD

**Issue by sagarpatel8384** [GoogleChromeLabs/ndb#256]
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.43
* Platform / OS version: Mac OSX Mojave
* Node.js version: v11.14.0

**What steps will reproduce the problem?**
`ndb server.js`

**What is the expected result?**
An instance of NDB/Chromium should open with an icon that is different from the original chrome browser icon. The Chromium (blue) icon should appear or the user should be able to customize the icon.

**What happens instead?**
A new instance of chrome is opened with the same exact icon as the original chrome browser. This makes it difficult/annoying to know which instance is your regular chrome browser vs. which is your debugger when Tab Switching between Code Editor, Browser, and NDB instance. 

![screenshot](https://user-images.githubusercontent.com/10161682/58636954-6b2d3500-82bf-11e9-92ed-fd687d86a3de.png)

**Comment by LeoBakerHytch** [comment]
This is caused by the change introduced in 1ab354468b1bf177fac1ac3834586d842e22f074, where `carlo` launches Chrome with the stable branch if it’s available, meaning it uses the system `Chrome.app`. You can fix this yourself by removing `'stable'` from the `carlo` options in [launcher.js#L24](https://github.com/GoogleChromeLabs/ndb/blob/6b2efdba9ab374157a5a7dc95d9c8d26eee3086d/lib/launcher.js#L24). Debatable as to what the desired default behaviour should be,

**Comment by sagarpatel8384** [comment]
Great, that worked. Thanks for the help!

**Comment by ak239** [comment]
Better icon is coming: https://github.com/GoogleChromeLabs/ndb/pull/260
